kind: pipeline
type: exec
name: deploy

trigger:
    branch:
        - main

clone:
    disable: true

steps:
    - name: pull
      commands:
          - cd /data/commspt-bot-avilla/ && proxychains4 -q git pull origin main

    - name: install dependencies
      commands:
          - docker pull registry1.fw.ac.cn/library/commspt-bot-avilla:latest
          - docker run -v /data/commspt-bot-avilla:/app --rm -e "PDM_PYPI_URL=https://mirror.nju.edu.cn/pypi/web/simple" registry1.fw.ac.cn/library/commspt-bot-avilla:latest /opt/pdm/bin/pdm sync --clean --prod

    - name: restart
      commands:
          - docker kill commspt-bot-avilla
          - docker start commspt-bot-avilla


node:
    lxc: "111"
    exec: "true"
